# i18n.toml

[options]
# 기본 로케일 (번역을 찾을 수 없을 때 폴백으로 사용됨)
default_locale = "en"
# 번역 파일이 있는 디렉토리
dir = "locales"
# 번역되지 않은 키를 숨길지 여부
hide_untranslated = false

# 다음 섹션은 일반적으로 필요하지 않지만, 특정 규칙을 정의할 때 사용됩니다.
# [[rules]]
# locales = ["en"]
# dir = "locales"